server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

client:
  client-id: ephI80bgH88cCS0nAdUEexTZgaIa #Change client-id
  client-secret: 9yWBvSfhvtWalnrT55QvGVyOe8Ia # Change client-secret
  post-logout-uri: http://localhost:8080/auth/login
  scope: openid
  authorization-grant-type: authorization_code
  grant-type: password

provider:
  host: https://localhost:9443

logging.level.com.etisalat.apigateway.client.WsoClient: DEBUG
allowed:
  origins: true

spring:
  cloud:
    gateway:
      routes:
        - id: ecare-appointment-service
          uri: lb://ecare-appointment-service
          predicates:
            - Path=/api/ecare/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
    discovery:
      enabled: true
    config:
      uri: http://localhost:8080

jwt:
  secret: ephI80bgH88cCS0nAdUEexTZgaIa
